const KEY='today-kakei-v2';
const defaults={version:3,settings:{salaryDay:15,salaryRule:'fixed',accountBalance:43629,minBalance:0},incomeTypes:['給料','その他'],categories:['食費','交通費','日用品','娯楽','美容','衣服','学費','サブスク','その他'],incomes:[],expenses:[],plans:[],goals:{},cards:[],subscriptions:[]};
const legacy=JSON.parse(localStorage.getItem('today-kakei-v1')||'null');
let data=JSON.parse(localStorage.getItem(KEY)||'null')||legacy||structuredClone(defaults);
data={...structuredClone(defaults),...data,settings:{...defaults.settings,...(data.settings||{})},goals:data.goals||{},cards:data.cards||[],subscriptions:data.subscriptions||[]};
if(data.settings.accountBalance===null||data.settings.accountBalance===''||!Number.isFinite(Number(data.settings.accountBalance)))data.settings.accountBalance=43629;
if(!Number.isFinite(Number(data.settings.minBalance)))data.settings.minBalance=0;
data.version=3;
// Older versions stored categories as plain text. Keep every existing name selectable after migration.
for(const item of [...data.expenses,...data.plans,...data.subscriptions])if(item.category&&!data.categories.includes(item.category))data.categories.push(item.category);
let selectedStart=null,recordFilter='all',planFilter='all',recordSearch='',recordCategoryFilter='',recordPaymentFilter='',recordCardFilter='';
const $=s=>document.querySelector(s),sum=xs=>xs.reduce((n,x)=>n+Number(x.amount||0),0);
const yen=n=>`${n<0?'−':''}¥${Math.abs(Math.round(n||0)).toLocaleString('ja-JP')}`;
const localDate=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
const today=()=>localDate(new Date()),uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}${Math.random()}`;
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const esc=t=>String(t||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dateObj=s=>new Date(`${s}T00:00:00`),fmtDate=s=>{const d=dateObj(s);return `${d.getMonth()+1}月${d.getDate()}日`};
function paydayInMonth(year,monthIndex){const d=Math.min(Number(data.settings.salaryDay),new Date(year,monthIndex+1,0).getDate());return localDate(new Date(year,monthIndex,d));}
function periodForDate(date=today()){
  const d=dateObj(date),thisPay=paydayInMonth(d.getFullYear(),d.getMonth());
  const start=date>=thisPay?thisPay:paydayInMonth(d.getFullYear(),d.getMonth()-1);
  const s=dateObj(start),next=paydayInMonth(s.getFullYear(),s.getMonth()+1),end=localDate(new Date(dateObj(next).getTime()-86400000));
  return {start,next,end,key:start};
}
function selectedPeriod(){return selectedStart?periodForDate(selectedStart):periodForDate();}
function inPeriod(item,p,key='date'){const v=item[key]||'';return v>=p.start&&v<p.next;}
function plansForPeriod(p){
  const months=[p.start.slice(0,7),p.next.slice(0,7)];
  const sources=[...data.plans.filter(x=>!x.paid),...data.subscriptions.filter(x=>x.status!=='stopped').map(x=>({...x,repeat:true,subscription:true}))];
  const settled=id=>data.expenses.some(expense=>expense.plannedId===id);
  return sources.flatMap(plan=>{
    const startDate=plan.startDate||plan.dueDate,endDate=plan.endDate||null;
    if(plan.subscription&&plan.frequency==='yearly'){
      const origin=dateObj(plan.dueDate),candidates=months.map(month=>`${month}-${String(Math.min(origin.getDate(),new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate())).padStart(2,'0')}`);
      return candidates.filter(dueDate=>dateObj(dueDate).getMonth()===origin.getMonth()&&dueDate>=p.start&&dueDate<p.next&&dueDate>=startDate&&(!endDate||dueDate<=endDate)).map(dueDate=>({...plan,id:`${plan.id}:${dueDate}`,sourceId:plan.id,dueDate})).filter(x=>!settled(x.id));
    }
    if(inPeriod(plan,p,'dueDate')&&plan.dueDate>=startDate&&(!endDate||plan.dueDate<=endDate))return settled(plan.id)?[]:[{...plan,sourceId:plan.id}];
    if(!plan.repeat)return [];
    return months.flatMap(month=>{
      if(plan.dueDate.slice(0,7)>month)return [];
      const day=Math.min(Number(plan.dueDate.slice(8,10)),new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate());
      const dueDate=`${month}-${String(day).padStart(2,'0')}`;
      return dueDate>=p.start&&dueDate<p.next&&dueDate>=startDate&&(!endDate||dueDate<=endDate)&&!settled(`${plan.id}:${month}`)?[{...plan,id:`${plan.id}:${month}`,sourceId:plan.id,dueDate}]:[];
    });
  });
}
function periodInfo(p=selectedPeriod()){
  const isCurrent=p.start===periodForDate().start,displayDate=isCurrent?today():(p.start<today()?p.end:p.start);
  const totalDays=Math.round((dateObj(p.next)-dateObj(p.start))/86400000), elapsed=Math.max(0,Math.round((dateObj(displayDate)-dateObj(p.start))/86400000));
  const daysLeft=Math.max(1,Math.round((dateObj(p.next)-dateObj(displayDate))/86400000));
  const incomes=data.incomes.filter(x=>inPeriod(x,p)),expenses=data.expenses.filter(x=>inPeriod(x,p)),plans=plansForPeriod(p);
  const income=sum(incomes),actual=sum(expenses),planned=sum(plans),goal=Number(data.goals[p.key]||0);
  const freeBeforeActual=income-planned-goal,remainingFree=freeBeforeActual-actual;
  const historical=expenses.filter(x=>x.date<displayDate),todayExpenses=expenses.filter(x=>x.date===displayDate);
  // The remaining free amount is the single source of truth. Actual spending is already deducted here.
  // Carryover is displayed only as yesterday's result; it is never added/subtracted a second time.
  const basic=Math.round(remainingFree/daysLeft),yesterday=localDate(new Date(dateObj(displayDate).getTime()-86400000));
  const yesterdayExpenses=expenses.filter(x=>x.date===yesterday),beforeYesterday=expenses.filter(x=>x.date<yesterday);
  const daysAtYesterday=Math.max(1,Math.round((dateObj(p.next)-dateObj(yesterday))/86400000));
  const yesterdayBase=Math.round((freeBeforeActual-sum(beforeYesterday))/daysAtYesterday),carry=yesterday>=p.start?yesterdayBase-sum(yesterdayExpenses):0;
  const todaySpent=sum(todayExpenses),available=basic;
  return {...p,isCurrent,displayDate,totalDays,elapsed,daysLeft,incomes,expenses,plans,income,actual,planned,goal,freeBeforeActual,remainingFree,basic,carry,todaySpent,available};
}
function periodText(p){return `${dateObj(p.start).getMonth()+1}/${dateObj(p.start).getDate()}〜${dateObj(p.end).getMonth()+1}/${dateObj(p.end).getDate()}`}
function iconForCategory(category){return ({'食費':'⌁','交通費':'⇄','日用品':'□','娯楽':'◇','美容':'○','衣服':'♢','学費':'▤','サブスク':'↻','その他':'•'})[category]||'•'}
function paymentText(payment){return ({cash:'現金',debit:'デビット',card:'クレジットカード',other:'その他'})[payment]||payment||'その他'}
function recordHtml(x,type){const label=type==='income'?(x.type||'その他'):(x.content||x.category||'支出'),card=x.cardId?data.cards.find(c=>c.id===x.cardId):null,detail=type==='income'?`${x.date} ・ ${x.type||'その他'}`:`${x.date} ・ ${x.category||'その他'} ・ ${paymentText(x.payment)}${card?' ・ '+card.name:''}`,actions=type==='expense'?`<div class="record-actions"><button class="edit-button" data-edit-expense="${x.id}">編集</button>${x.plannedId?`<button class="edit-button" data-delete="unsettle" data-id="${x.id}">予定に戻す</button>`:''}<button class="icon-button" data-delete="expense" data-id="${x.id}" aria-label="削除">削除</button></div>`:`<div class="record-actions"><button class="icon-button" data-delete="income" data-id="${x.id}" aria-label="削除">削除</button></div>`;return `<article class="record ${type}"><div class="record-icon">${type==='income'?'↓':iconForCategory(x.category)}</div><div class="record-main"><div class="record-primary"><b>${esc(label)}</b><strong class="record-amount ${type==='income'?'income':''}">${type==='income'?'+':'−'}${yen(x.amount)}</strong></div><small>${esc(detail)}</small></div>${actions}</article>`}
function planState(x){if(x.dueDate<today())return {key:'overdue',label:'支払予定日を過ぎています'};if(x.dueDate===today())return {key:'today',label:'今日支払予定'};return {key:'upcoming',label:'今後の予定'}}
function planHtml(x){const state=planState(x),urgent=state.key==='today'||state.key==='overdue';return `<article class="record"><div class="record-icon">${iconForCategory(x.category)}</div><div class="record-main"><div class="record-primary"><b>${esc(x.content||'予定支出')}</b><strong class="record-amount">${yen(x.amount)}</strong></div><small>${x.dueDate} ・ ${esc(x.category||'その他')} ・ ${paymentText(x.payment)}</small><i class="status-badge ${state.key}">${state.label}</i></div><div class="record-actions"><button class="edit-button ${urgent?'settle-button':''}" data-settle-plan="${x.id}">実績化</button><button class="icon-button" data-delete="plan" data-id="${x.sourceId||x.id}" aria-label="削除">削除</button></div></article>`}
function nextSubscriptionDate(x,from=today()){if(x.status==='stopped')return null;const start=x.startDate||x.dueDate,end=x.endDate||null,origin=dateObj(x.dueDate);let y=dateObj(from).getFullYear(),m=dateObj(from).getMonth();for(let attempt=0;attempt<24;attempt++){const d=paydayDay(y,m,origin.getDate());if(x.frequency==='yearly'&&m!==origin.getMonth()){m++;if(m===12){m=0;y++}continue}if(d>=from&&d>=start&&(!end||d<=end))return d;m++;if(m===12){m=0;y++}}return null}
function subscriptionAmounts(x){const monthly=x.frequency==='yearly'?Number(x.amount)/12:Number(x.amount);return {monthly,annual:monthly*12}}
function subscriptionHtml(x){const state=x.status==='stopped'?'停止中':'利用中',card=data.cards.find(c=>c.id===x.cardId),next=nextSubscriptionDate(x),a=subscriptionAmounts(x),freq=x.frequency==='yearly'?'年払い':'毎月';return `<article class="record"><div class="record-icon">↻</div><div class="record-main"><div class="record-primary"><b>${esc(x.content||'サブスクリプション')}</b><strong class="record-amount">${yen(x.amount)}</strong></div><small>${freq} ・ 次回 ${next?fmtDate(next):'なし'} ・ 月額換算 ${yen(a.monthly)} ・ 年間 ${yen(a.annual)}<br>${esc(x.category||'その他')} ・ ${state}${card?' ・ '+esc(card.name):''}</small></div><div class="record-actions"><button class="edit-button" data-edit-subscription="${x.id}">編集</button><button class="edit-button" data-toggle-subscription="${x.id}">${x.status==='stopped'?'再開':'停止'}</button><button class="icon-button" data-delete-subscription="${x.id}" aria-label="削除">削除</button></div></article>`}
function cardPaymentDate(item){const card=data.cards.find(x=>x.id===item.cardId),usedOn=item.date||item.dueDate;if(!card||!usedOn)return null;const d=dateObj(usedOn),close=Math.min(Number(card.closeDay),new Date(d.getFullYear(),d.getMonth()+1,0).getDate());const offset=d.getDate()<=close?1:2;return paydayDay(d.getFullYear(),d.getMonth()+offset,Number(card.paymentDay));}
function paydayDay(year,monthIndex,day){return localDate(new Date(year,monthIndex,Math.min(day,new Date(year,monthIndex+1,0).getDate())));}
function cardCharges(){const p=selectedPeriod(),items=[...data.expenses.filter(x=>x.cardId).map(x=>({...x,usedOn:x.date,kind:'利用'})),...plansForPeriod(p).filter(x=>x.cardId&&!x.paid&&x.dueDate>=today()).map(x=>({...x,usedOn:x.dueDate,kind:'予定利用'}))];return items.map(x=>({...x,billDate:cardPaymentDate(x)})).filter(x=>x.billDate)}
function bankInfo(p=selectedPeriod()){const balance=Number(data.settings.accountBalance||0),minimum=Number(data.settings.minBalance||0),directPlans=plansForPeriod(p).filter(x=>x.dueDate>=today()&&x.dueDate<p.next&&!x.cardId),cardBills=cardCharges().filter(x=>x.billDate>=today()&&x.billDate<p.next),direct=sum(directPlans),card=sum(cardBills),outflows=direct+card,after=balance-outflows,additional=Math.max(0,after-minimum),shortfall=Math.max(0,minimum-after);return {balance,minimum,direct,card,outflows,after,additional,shortfall,cardAfterPay:sum(cardCharges().filter(x=>x.billDate>=p.next))}}
function ensureFinanceUI(){if(!$('#bankBalance')){$('#dashboard .stat-grid').insertAdjacentHTML('afterend','<section class="bank-overview"><div class="section-heading minor"><div><p class="eyebrow">ACTUAL CASH FLOW</p><h3>口座から見た資金余力</h3></div></div><div class="bank-grid"><article><span>現在の銀行残高</span><strong id="bankBalance">¥0</strong></article><article><span>今後の支払い予定</span><strong id="futureOutflows">¥0</strong></article><article><span>予定支払い後の残高</span><strong id="afterOutflows">¥0</strong></article></div><p id="bankBreakdown" class="bank-breakdown"></p></section>')}if(!$('#bankSettingSummary')){$('#manage .manage-row').insertAdjacentHTML('afterend','<article class="manage-row bank-setting"><div><span>現在の銀行残高</span><strong id="bankSettingSummary">¥0</strong><small id="minBalanceSummary">最低残高 ¥0</small></div><button class="outline" data-open="settings">変更</button></article>')}const subManage=document.querySelector('[data-tab="subscriptionsManage"]');if(subManage)subManage.textContent='管理 ＞'}
function cardBillHtml(){const charges=cardCharges(),groups={};for(const c of charges){const key=`${c.cardId}:${c.billDate}`;(groups[key]??=[]).push(c)}const entries=Object.entries(groups).sort((a,b)=>a[1][0].billDate.localeCompare(b[1][0].billDate));return entries.length?entries.map(([,items],index)=>{const first=items[0],card=data.cards.find(x=>x.id===first.cardId),total=sum(items);return `<details class="card-bill ${index===0?'next-card-bill':''}"><summary><div class="record-icon">▣</div><div class="record-main"><div class="record-primary"><b>${esc(card?.name||'クレジットカード')}</b><strong class="record-amount">${yen(total)}</strong></div><small>${fmtDate(first.billDate)}請求 ・ ${items.length}件</small></div><span class="detail-toggle">明細を見る ▼</span></summary><div class="card-bill-details">${items.map(x=>`<div><span>${x.usedOn}　${esc(x.content||x.category||'利用')}</span><b>${yen(x.amount)}</b></div>`).join('')}</div></details>`}).join(''):'カード請求予定はありません'}
function nextCardBill(){const groups={};for(const charge of cardCharges().filter(x=>x.billDate>=today())){const key=`${charge.cardId}:${charge.billDate}`;(groups[key]??=[]).push(charge)}const first=Object.values(groups).sort((a,b)=>a[0].billDate.localeCompare(b[0].billDate))[0];if(!first)return null;return {date:first[0].billDate,card:data.cards.find(x=>x.id===first[0].cardId),amount:sum(first)}}
function cashflowHtml(){const p=selectedPeriod(),events=[];for(const income of data.incomes.filter(x=>x.date>=today()))events.push({date:income.date,amount:Number(income.amount),label:`収入：${income.type||'その他'}`});for(const charge of cardCharges().filter(x=>x.billDate>=today()))events.push({date:charge.billDate,amount:-Number(charge.amount),label:`${data.cards.find(x=>x.id===charge.cardId)?.name||'カード'}引落`});for(const plan of plansForPeriod(p).filter(x=>x.dueDate>=today()&&!x.paid&&!x.cardId))events.push({date:plan.dueDate,amount:-Number(plan.amount),label:plan.content||'予定支出'});if(!data.incomes.some(x=>x.date===p.next&&x.type==='給料'))events.push({date:p.next,amount:null,label:'給料予定：未入力'});events.sort((a,b)=>a.date.localeCompare(b.date));let balance=Number(data.settings.accountBalance);return events.length?events.slice(0,8).map(x=>{if(x.amount!==null&&Number.isFinite(balance))balance+=x.amount;return `<article class="record"><div class="record-icon">◷</div><div class="record-main"><b>${esc(x.label)}</b><small>${x.date}${Number.isFinite(balance)?` ・ 残高見込 ${yen(balance)}`:''}</small></div><strong class="record-amount ${x.amount>0?'income':''}">${x.amount===null?'未入力':(x.amount>0?'+':'−')+yen(Math.abs(x.amount))}</strong></article>`}).join(''):'口座残高と予定を設定すると表示されます'}
function render(){
  ensureFinanceUI();const i=periodInfo(),p=i,bank=bankInfo(p);$('#periodLabel').textContent=periodText(p);$('#monthInput').value=p.start.slice(0,7);
  const over=i.remainingFree<0;$('#heroLabel').textContent='今追加で使える金額';$('#todayAvailable').textContent=yen(bank.additional);$('#dailyBaseLabel').textContent=over?'今期の予算超過':'今期の予算残高';$('#dailyBase').textContent=yen(Math.abs(i.remainingFree));$('#carryover').textContent=over?`残り${i.daysLeft}日で1日平均 ${yen(Math.abs(i.basic))} 少なく使う目安`:'給料期間の予算内です';$('#carryover').className=over?'danger':'';$('#todaySpent').textContent=yen(i.todaySpent);
  $('#remainingFree').textContent=yen(i.remainingFree);$('#daysLeft').textContent=`あと${i.daysLeft}日`;$('#nextPayday').textContent=fmtDate(i.next);$('#periodDescription').textContent=`給料期間：${periodText(p)}`;$('#heroMessage').textContent=bank.shortfall?`最低残高まであと${yen(bank.shortfall)}の調整が必要です。`:`最低残高 ${yen(bank.minimum)} を残したうえで使える金額です。`;$('#heroCard').classList.toggle('negative',bank.shortfall>0);$('#bankBalance').textContent=yen(bank.balance);$('#futureOutflows').textContent=yen(bank.outflows);$('#afterOutflows').textContent=yen(bank.after);$('#bankBreakdown').textContent=`内訳：口座から直接支払う予定 ${yen(bank.direct)} ・ カード引き落とし ${yen(bank.card)}${bank.cardAfterPay?` ・ 次の給料日後のカード請求 ${yen(bank.cardAfterPay)}`:''}`;$('#bankSettingSummary').textContent=yen(bank.balance);$('#minBalanceSummary').textContent=`最低残高 ${yen(bank.minimum)}`;
  const nextBill=nextCardBill();$('#nextCardBill').hidden=!nextBill;if(nextBill){$('#nextCardBillAmount').textContent=yen(nextBill.amount);$('#nextCardBillDetail').textContent=`${fmtDate(nextBill.date)} ・ ${nextBill.card?.name||'クレジットカード'}${nextBill.date<i.next?'（次の給料日前）':''}`}
  const recent=[...i.expenses].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);$('#recentExpenses').className=`record-list${recent.length?'':' empty'}`;$('#recentExpenses').innerHTML=recent.length?recent.map(x=>recordHtml(x,'expense')).join(''):'まだ支出はありません';
  const needsAttention=i.plans.filter(x=>x.dueDate<=today()).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));$('#attentionList').className=`record-list${needsAttention.length?'':' empty small-empty'}`;$('#attentionList').innerHTML=needsAttention.length?needsAttention.map(planHtml).join(''):'確認が必要な項目はありません';
  const categorySelect=$('#recordCategoryFilter'),cardSelect=$('#recordCardFilter');categorySelect.innerHTML=`<option value="">すべて</option>${data.categories.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}`;categorySelect.value=recordCategoryFilter;cardSelect.innerHTML=`<option value="">すべて</option>${data.cards.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}`;cardSelect.value=recordCardFilter;
  const needle=recordSearch.trim().toLowerCase();const records=[...i.expenses.map(x=>({...x,_type:'expense'})),...i.incomes.map(x=>({...x,_type:'income'}))].filter(x=>recordFilter==='all'||x._type===recordFilter).filter(x=>!needle||`${x.content||''} ${x.category||''} ${x.type||''} ${x.memo||''}`.toLowerCase().includes(needle)).filter(x=>!recordCategoryFilter||x.category===recordCategoryFilter).filter(x=>!recordPaymentFilter||x.payment===recordPaymentFilter).filter(x=>!recordCardFilter||x.cardId===recordCardFilter).sort((a,b)=>b.date.localeCompare(a.date));$('#allRecords').className=`record-list${records.length?'':' empty'}`;$('#allRecords').innerHTML=records.length?records.map(x=>recordHtml(x,x._type)).join(''):'条件に合う記録はありません';
  const activeSubscriptions=data.subscriptions.filter(x=>x.status!=='stopped'&&(!x.endDate||x.endDate>=today())),subscriptionMonthly=activeSubscriptions.reduce((n,x)=>n+subscriptionAmounts(x).monthly,0),subscriptionAnnual=activeSubscriptions.reduce((n,x)=>n+subscriptionAmounts(x).annual,0);$('#savingGoalDisplay').textContent=yen(i.goal);$('#salaryDayDisplay').textContent=`${data.settings.salaryDay}日`;$('#categoryCount').textContent=`${data.categories.length}件`;$('#cardCount').textContent=`${data.cards.length}枚`;$('#subscriptionSummary').textContent=`${activeSubscriptions.length}件 ・ 月額 ${yen(subscriptionMonthly)}`;$('#subscriptionAnnual').textContent=`年間 ${yen(subscriptionAnnual)}`;$('#subscriptionList').className=`record-list compact-list${data.subscriptions.length?'':' empty'}`;$('#subscriptionList').innerHTML=data.subscriptions.length?[...data.subscriptions].map(subscriptionHtml).join(''):'サブスクリプションはありません';$('#cardList').className=`record-list compact-list${data.cards.length?'':' empty'}`;$('#cardList').innerHTML=data.cards.length?data.cards.map(card=>`<article class="record"><div class="record-icon">▣</div><div class="record-main"><b>${esc(card.name)}</b><small>毎月${card.closeDay}日締め ・ 翌月以降${card.paymentDay}日払い</small></div></article>`).join(''):'カードは未登録です';
  const visiblePlans=i.plans.filter(x=>planFilter==='all'||planState(x).key===planFilter).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));$('#planSummary').textContent=i.plans.length?`未払い ${i.plans.length}件 ・ ${yen(sum(i.plans))}`:'';$('#planList').className=`record-list${visiblePlans.length?'':' empty'}`;$('#planList').innerHTML=visiblePlans.length?visiblePlans.map(planHtml).join(''):'この条件の予定支出はありません';
  $('#totalIncome').textContent=yen(i.income);$('#totalExpense').textContent=yen(i.actual);$('#totalPlans').textContent=yen(i.planned);$('#goalAmount').textContent=yen(i.goal);
  const byCat={};i.expenses.forEach(x=>byCat[x.category||'その他']=(byCat[x.category||'その他']||0)+Number(x.amount));const entries=Object.entries(byCat).sort((a,b)=>b[1]-a[1]);$('#categoryChart').className=`chart${entries.length?'':' empty'}`;$('#categoryChart').innerHTML=entries.length?entries.map(([c,v])=>`<div class="chart-row"><div class="chart-label"><span>${esc(c)}</span><b>${yen(v)} (${Math.round(v/i.actual*100)}%)</b></div><div class="bar"><i style="width:${v/i.actual*100}%"></i></div></div>`).join(''):'支出を追加すると、ここに内訳が表示されます';
  const average=i.elapsed?Math.round(i.actual/Math.max(1,i.elapsed+1)):i.actual,top=entries[0]?.[0]||'まだありません',usage=i.freeBeforeActual?Math.round(i.actual/i.freeBeforeActual*100):0;$('#analysisInsights').innerHTML=`<b>かんたんサマリー</b><span>期間中の1日平均支出 ${yen(average)} ・ 最も多いカテゴリー ${esc(top)} ・ 自由費の消化率 ${usage}%</span>`;const previous=periodInfo(periodForDate(localDate(new Date(dateObj(p.start).getTime()-86400000)))),previousByCat={};previous.expenses.forEach(x=>previousByCat[x.category||'その他']=(previousByCat[x.category||'その他']||0)+Number(x.amount));const comparison=[...new Set([...Object.keys(byCat),...Object.keys(previousByCat)])].slice(0,5);$('#periodComparison').className=`comparison${comparison.length?'':' empty'}`;$('#periodComparison').innerHTML=comparison.length?comparison.map(c=>`<div class="comparison-row"><b>${esc(c)}</b><span>今期 ${yen(byCat[c]||0)} ／ 前期 ${yen(previousByCat[c]||0)}</span></div>`).join(''):'前の期間の記録があると表示されます';
  $('#calculationExplanation').textContent=`${periodText(p)}の収入 ${yen(i.income)} − 未払い予定 ${yen(i.planned)} − 貯金目標 ${yen(i.goal)} ＝ 自由費 ${yen(i.freeBeforeActual)}。実績支出 ${yen(i.actual)} を引いた残りは ${yen(i.remainingFree)} です。`;$('#cardBillList').className=`record-list${cardCharges().length?'':' empty'}`;$('#cardBillList').innerHTML=cardBillHtml();const simCard=$('#simulationCard');const selectedCard=simCard.value;simCard.innerHTML=`<option value="">カードを選択</option>${data.cards.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}`;simCard.value=selectedCard;syncSimulationCard();simulate();
}
function syncSimulationCard(){const isCard=$('#simulationPayment').value==='card';$('#simulationCardField').hidden=!isCard;$('#registerSimulation').hidden=!Number($('#simulationAmount').value||0)}
function simulate(){const value=Number($('#simulationAmount').value||0),i=periodInfo(),bank=bankInfo(i),method=$('#simulationPayment').value,cardId=$('#simulationCard').value;if(!value){$('#simulationResult').textContent='金額を入れると、給料期間の予算と口座から見た資金余力の変化を確認できます。';$('#registerSimulation').hidden=true;return}const before=Math.round(i.remainingFree/i.daysLeft),after=Math.round((i.remainingFree-value)/i.daysLeft);let bankImpact=value,extra='';if(method==='card'){if(!cardId){extra='<br><strong class="danger">カードを選択すると引き落とし予定日を確認できます。</strong>';bankImpact=0}else{const billDate=cardPaymentDate({date:today(),cardId}),current=sum(cardCharges().filter(x=>x.cardId===cardId&&x.billDate===billDate));if(billDate>=i.next){bankImpact=0;extra=`<br>引き落とし予定日：<b>${fmtDate(billDate)}</b>（次の給料日後）<br>次の給料後のカード請求：<b>${yen(current)} → ${yen(current+value)}</b>`}else extra=`<br>引き落とし予定日：<b>${fmtDate(billDate)}</b><br>その日のカード請求：<b>${yen(current)} → ${yen(current+value)}</b>`}}const afterBank=bank.after-bankImpact,afterAdditional=Math.max(0,afterBank-bank.minimum),shortfall=Math.max(0,bank.minimum-afterBank);$('#simulationResult').innerHTML=`給料期間の予算：<b>${yen(i.remainingFree)}</b> → <b>${yen(i.remainingFree-value)}</b>（1日予算 ${yen(before)} → ${yen(after)}）<br>予定支払い後の口座残高：<b>${yen(bank.after)}</b> → <b>${yen(afterBank)}</b><br><strong class="${shortfall?'danger':''}">購入後に追加で使える金額：${yen(afterAdditional)}${shortfall?`（最低残高まであと${yen(shortfall)}）`:''}</strong>${extra}`;$('#registerSimulation').hidden=false}
function registerSimulation(){const amount=Number($('#simulationAmount').value||0),method=$('#simulationPayment').value,cardId=$('#simulationCard').value;if(!amount||method==='card'&&!cardId){alert('金額と、クレジットカードの場合はカードを選択してください。');return}data.expenses.push({id:uid(),amount,date:today(),category:'その他',content:'シミュレーションから登録',payment:method,cardId:method==='card'?cardId:'',memo:''});save();$('#simulationAmount').value='';render();alert('支出として登録しました。')}
const field=(label,input)=>`<label class="field"><span>${label}</span>${input}</label>`;
function syncEntryCard(){const method=document.querySelector('#entryForm [name="payment"]'),cardField=document.querySelector('[data-entry-card-field]');if(cardField&&method)cardField.hidden=method.value!=='card'}
function openForm(kind,editId=null){const d=$('#entryDialog'),now=today(),options=(selected='')=>data.categories.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join(''),types=data.incomeTypes.map(x=>`<option>${esc(x)}</option>`).join(''),cardOptions=(selected='')=>`<option value="">現金・その他</option>${data.cards.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${esc(x.name)}</option>`).join('')}`,existing=editId?data.expenses.find(x=>x.id===editId):null,existingSubscription=editId?data.subscriptions.find(x=>x.id===editId):null;let title='',fields='';
 if(kind==='settle'){const plan=plansForPeriod(selectedPeriod()).find(x=>x.id===editId);if(!plan){alert('この予定支出はすでに実績化済みか、見つかりません。');return}const method=plan.cardId?'card':(plan.payment||'cash');title='予定支出を実績化';fields=`<p class="explanation">未払い予定から外し、実績支出として記録します。残り自由費は変わりません。</p>`+field('支出名',`<input name="content" value="${esc(plan.content||'予定支出')}" required>`)+field('金額（円）',`<input name="amount" type="number" inputmode="numeric" min="1" value="${plan.amount}" required>`)+field('実際の支払日',`<input name="date" type="date" value="${today()}" required>`)+field('カテゴリー',`<select name="category">${options(plan.category||'その他')}</select>`)+field('支払方法',`<select name="payment"><option value="cash" ${method==='cash'?'selected':''}>現金</option><option value="debit" ${method==='debit'?'selected':''}>デビット</option><option value="card" ${method==='card'?'selected':''}>クレジットカード</option><option value="other" ${method==='other'?'selected':''}>その他</option></select>`)+`<label class="field" data-entry-card-field><span>使用したカード</span><select name="cardId">${cardOptions(plan.cardId||'')}</select></label>`+field('メモ（任意）',`<textarea name="memo">${esc(plan.memo||'')}</textarea>`)}
 if(kind==='expense'){title=existing?'支出を編集':'支出を追加';const latest=[...data.expenses].sort((a,b)=>b.date.localeCompare(a.date))[0],x=existing||{amount:'',category:latest?.category||'食費',content:'',date:now,payment:latest?.payment||'cash',memo:'',cardId:latest?.cardId||''},method=x.cardId?'card':(x.payment||'cash');fields=field('金額（円）',`<input name="amount" type="number" inputmode="numeric" min="1" value="${x.amount}" required autofocus>`)+field('カテゴリ',`<select name="category" required>${options(x.category)}</select>`)+field('内容（任意）',`<input name="content" value="${esc(x.content)}" placeholder="例：コンビニ">`)+field('支出日',`<input name="date" type="date" value="${x.date}" required>`)+field('支払方法',`<select name="payment"><option value="cash" ${method==='cash'?'selected':''}>現金</option><option value="debit" ${method==='debit'?'selected':''}>デビット</option><option value="card" ${method==='card'?'selected':''}>クレジットカード</option><option value="other" ${method==='other'?'selected':''}>その他</option></select>`)+`<label class="field" data-entry-card-field><span>使用するカード</span><select name="cardId">${cardOptions(x.cardId)}</select></label>`+field('メモ（任意）',`<textarea name="memo">${esc(x.memo)}</textarea>`)}
 if(kind==='income'){title='収入を追加';fields=field('金額（円）','<input name="amount" type="number" inputmode="numeric" min="1" required autofocus>')+field('入金日',`<input name="date" type="date" value="${now}" required>`)+field('収入の種類',`<input name="type" list="incomeTypes" value="給料" required><datalist id="incomeTypes">${types}</datalist>`)+field('メモ（任意）','<textarea name="memo"></textarea>')+field('予定収入','<label class="check"><input name="expected" type="checkbox"> 予定として登録する</label>')}
 if(kind==='plan'){title='予定支出を追加';fields=field('金額（円）','<input name="amount" type="number" inputmode="numeric" min="1" required autofocus>')+field('支出予定日',`<input name="dueDate" type="date" value="${now}" required>`)+field('内容','<input name="content" required placeholder="例：美容室">')+field('カテゴリ',`<select name="category" required>${options('その他')}</select>`)+field('支払方法','<select name="payment"><option value="cash">現金</option><option value="debit">デビット</option><option value="card">クレジットカード</option><option value="other">その他</option></select>')+`<label class="field" data-entry-card-field><span>使用するカード</span><select name="cardId">${cardOptions()}</select></label>`+field('状態','<label class="check"><input name="paid" type="checkbox"> すでに支払った</label>')+field('繰り返し','<label class="check"><input name="repeat" type="checkbox"> 毎月同じ予定を登録する</label>')+field('メモ（任意）','<textarea name="memo"></textarea>')}
 if(kind==='saving'){const p=selectedPeriod();title='貯金目標を設定';fields=field(`${periodText(p)}に最低でも貯金したい金額（円）`,`<input name="amount" type="number" inputmode="numeric" min="0" value="${data.goals[p.key]||''}" required autofocus>`)}
 if(kind==='settings'){title='家計と口座残高の設定';fields=field('毎月の給料日（1〜31日）',`<input name="salaryDay" type="number" inputmode="numeric" min="1" max="31" value="${data.settings.salaryDay}" required autofocus>`)+field('現在の銀行残高（円）',`<input name="accountBalance" type="number" inputmode="numeric" min="0" value="${data.settings.accountBalance}" required>`)+field('最低残しておきたい金額（円）',`<input name="minBalance" type="number" inputmode="numeric" min="0" value="${data.settings.minBalance||0}" required>`)+`<p class="explanation">銀行残高は資金余力の確認専用です。給料期間の予算とは別に、次の給料日前までの口座引き落とし予定と最低残高を引いて「今追加で使える金額」を計算します。</p>`}
 if(kind==='card'){title='クレジットカードを追加';fields=field('カード名','<input name="name" required autofocus placeholder="例：楽天カード">')+field('締め日（毎月）','<input name="closeDay" type="number" inputmode="numeric" min="1" max="31" required>')+field('支払日（翌月以降）','<input name="paymentDay" type="number" inputmode="numeric" min="1" max="31" required>')}
 if(kind==='subscription'){const x=existingSubscription||{content:'',amount:'',dueDate:now,startDate:now,category:'サブスク',cardId:'',payment:'cash',memo:'',frequency:'monthly',endDate:''},method=x.cardId?'card':(x.payment||'cash');title=existingSubscription?'サブスクリプションを編集':'サブスクリプションを追加';fields=field('サービス名',`<input name="content" value="${esc(x.content)}" required autofocus placeholder="例：Netflix">`)+field('金額（円）',`<input name="amount" type="number" inputmode="numeric" min="1" value="${x.amount}" required>`)+field('支払日（基準日）',`<input name="dueDate" type="date" value="${x.dueDate}" required>`)+field('開始日',`<input name="startDate" type="date" value="${x.startDate||x.dueDate}" required>`)+field('カテゴリー',`<select name="category">${options(x.category)}</select>`)+field('支払方法',`<select name="payment"><option value="cash" ${method==='cash'?'selected':''}>現金</option><option value="debit" ${method==='debit'?'selected':''}>デビット</option><option value="card" ${method==='card'?'selected':''}>クレジットカード</option><option value="other" ${method==='other'?'selected':''}>その他</option></select>`)+`<label class="field" data-entry-card-field><span>使用するカード</span><select name="cardId">${cardOptions(x.cardId)}</select></label>`+field('繰り返し頻度',`<select name="frequency"><option value="monthly" ${x.frequency!=='yearly'?'selected':''}>毎月</option><option value="yearly" ${x.frequency==='yearly'?'selected':''}>年払い</option></select>`)+field('メモ（任意）',`<textarea name="memo">${esc(x.memo)}</textarea>`)+field('解約日（任意）',`<input name="endDate" type="date" value="${x.endDate||''}">`)}
 $('#modalTitle').textContent=title;$('#formFields').innerHTML=fields;$('#entryForm').dataset.kind=kind;$('#entryForm').dataset.editId=editId||'';d.showModal();syncEntryCard();}
function submitForm(e){e.preventDefault();const form=new FormData(e.currentTarget),kind=e.currentTarget.dataset.kind,obj=Object.fromEntries(form),editId=e.currentTarget.dataset.editId;if(obj.payment&&obj.payment!=='card')obj.cardId='';if(kind==='saving'){data.goals[selectedPeriod().key]=Number(obj.amount||0)}else if(kind==='settings'){data.settings.salaryDay=Math.max(1,Math.min(31,Number(obj.salaryDay)));data.settings.accountBalance=Math.max(0,Number(obj.accountBalance));data.settings.minBalance=Math.max(0,Number(obj.minBalance));selectedStart=null}else{obj.amount=Number(obj.amount);obj.repeat=!!obj.repeat;obj.expected=!!obj.expected;obj.paid=!!obj.paid;if(kind==='settle'){if(data.expenses.some(x=>x.plannedId===editId)){alert('この予定はすでに実績化済みです。');return}data.expenses.push({...obj,id:uid(),plannedId:editId})}else if(kind==='card'){obj.id=uid();obj.closeDay=Number(obj.closeDay);obj.paymentDay=Number(obj.paymentDay);data.cards.push(obj)}else if(kind==='subscription'&&editId){const index=data.subscriptions.findIndex(x=>x.id===editId);if(index>=0)data.subscriptions[index]={...data.subscriptions[index],...obj,id:editId,status:data.subscriptions[index].status||'active'}}else if(kind==='subscription'){obj.id=uid();obj.status='active';data.subscriptions.push(obj)}else if(kind==='expense'&&editId){const index=data.expenses.findIndex(x=>x.id===editId);if(index>=0)data.expenses[index]={...data.expenses[index],...obj,id:editId}}else{obj.id=uid();if(kind==='expense')data.expenses.push(obj);if(kind==='income')data.incomes.push(obj);if(kind==='plan')data.plans.push(obj)}if(obj.type&&!data.incomeTypes.includes(obj.type))data.incomeTypes.push(obj.type)}save();$('#entryDialog').close();render()}
function deleteItem(type,id){if(type==='unsettle'){unsettleExpense(id);return}if(!confirm('この記録を削除しますか？'))return;if(type==='plan'){data.plans=data.plans.filter(x=>x.id!==id);data.subscriptions=data.subscriptions.filter(x=>x.id!==id)}else{const key=type==='income'?'incomes':'expenses';data[key]=data[key].filter(x=>x.id!==id)}save();render()}
function settlePlan(occurrenceId){openForm('settle',occurrenceId)}
function unsettleExpense(id){const expense=data.expenses.find(x=>x.id===id);if(!expense?.plannedId)return;if(!confirm('この実績支出を削除し、元の未払い予定支出へ戻しますか？'))return;data.expenses=data.expenses.filter(x=>x.id!==id);save();render()}
function renderCategoryManager(){const list=$('#categoryList');list.innerHTML=data.categories.map((name,index)=>`<div class="category-row"><input data-category-input="${index}" value="${esc(name)}" maxlength="30" aria-label="${esc(name)}"><button data-category-rename="${index}" title="名前を保存">保存</button><button data-category-move="${index}" data-direction="up" title="上へ">↑</button><button data-category-move="${index}" data-direction="down" title="下へ">↓</button><button class="delete-category" data-category-delete="${index}" title="削除">×</button></div>`).join('')}
function renameCategory(index){const oldName=data.categories[index],input=document.querySelector(`[data-category-input="${index}"]`),newName=(input?.value||'').trim();if(!newName){alert('カテゴリー名を入力してください。');return}if(newName!==oldName&&data.categories.includes(newName)){alert('同じ名前のカテゴリーがすでにあります。');return}data.categories[index]=newName;for(const item of [...data.expenses,...data.plans,...data.subscriptions])if(item.category===oldName)item.category=newName;save();renderCategoryManager();render()}
function moveCategory(index,direction){const target=index+(direction==='up'?-1:1);if(target<0||target>=data.categories.length)return;[data.categories[index],data.categories[target]]=[data.categories[target],data.categories[index]];save();renderCategoryManager();render()}
function removeCategory(index){if(data.categories.length===1){alert('カテゴリーは1件以上必要です。');return}const name=data.categories[index],used=[...data.expenses,...data.plans,...data.subscriptions].filter(x=>x.category===name).length;if(used){const replacement=name!=='その他'&&data.categories.includes('その他')?'その他':data.categories.find(x=>x!==name);if(!confirm(`「${name}」は${used}件の支出・予定支出で使用されています。削除すると「${replacement}」へ変更します。続けますか？`))return;for(const item of [...data.expenses,...data.plans,...data.subscriptions])if(item.category===name)item.category=replacement}else if(!confirm(`「${name}」を削除しますか？`))return;data.categories.splice(index,1);save();renderCategoryManager();render()}
function addCategory(){const input=$('#newCategory'),name=input.value.trim();if(!name){alert('追加するカテゴリー名を入力してください。');return}if(data.categories.includes(name)){alert('同じ名前のカテゴリーがすでにあります。');return}data.categories.push(name);input.value='';save();renderCategoryManager();render()}
function backupData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`today-kakei-backup-${today()}.json`;link.click();URL.revokeObjectURL(link.href)}
function restoreData(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const restored=JSON.parse(reader.result);if(!restored||!Array.isArray(restored.expenses)||!confirm('現在のデータをバックアップファイルの内容へ置き換えますか？'))return;data={...structuredClone(defaults),...restored,settings:{...defaults.settings,...(restored.settings||{})},cards:restored.cards||[],subscriptions:restored.subscriptions||[],goals:restored.goals||{},version:3};save();render();alert('復元しました。')}catch{alert('バックアップファイルを読み込めませんでした。')}};reader.readAsText(file)}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===tab.dataset.tab));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b===tab));window.scrollTo({top:0,behavior:'smooth'});return}const open=e.target.closest('[data-open]');if(open){if(open.dataset.open==='categories'){renderCategoryManager();$('#categoryDialog').showModal()}else if(open.dataset.open==='simulation')$('#simulationDialog').showModal();else openForm(open.dataset.open);return}if(e.target.closest('[data-close]'))e.target.closest('dialog').close();const settle=e.target.closest('[data-settle-plan]');if(settle){settlePlan(settle.dataset.settlePlan);return}const edit=e.target.closest('[data-edit-expense]');if(edit){openForm('expense',edit.dataset.editExpense);return}const editSub=e.target.closest('[data-edit-subscription]');if(editSub){openForm('subscription',editSub.dataset.editSubscription);return}const toggleSub=e.target.closest('[data-toggle-subscription]');if(toggleSub){const sub=data.subscriptions.find(x=>x.id===toggleSub.dataset.toggleSubscription);if(sub){sub.status=sub.status==='stopped'?'active':'stopped';save();render()}return}const deleteSub=e.target.closest('[data-delete-subscription]');if(deleteSub){if(confirm('このサブスクリプションを削除しますか？ 過去に登録済みの支出は削除されません。')){data.subscriptions=data.subscriptions.filter(x=>x.id!==deleteSub.dataset.deleteSubscription);save();render()}return}const del=e.target.closest('[data-delete]');if(del)deleteItem(del.dataset.delete,del.dataset.id);const rename=e.target.closest('[data-category-rename]');if(rename)renameCategory(Number(rename.dataset.categoryRename));const move=e.target.closest('[data-category-move]');if(move)moveCategory(Number(move.dataset.categoryMove),move.dataset.direction);const remove=e.target.closest('[data-category-delete]');if(remove)removeCategory(Number(remove.dataset.categoryDelete));if(e.target.closest('#addCategory'))addCategory();const filter=e.target.closest('[data-record-filter]');if(filter){recordFilter=filter.dataset.recordFilter;document.querySelectorAll('[data-record-filter]').forEach(b=>b.classList.toggle('selected',b===filter));render();return}const planButton=e.target.closest('[data-plan-filter]');if(planButton){planFilter=planButton.dataset.planFilter;document.querySelectorAll('[data-plan-filter]').forEach(b=>b.classList.toggle('selected',b===planButton));render()}});
$('#entryForm').addEventListener('submit',submitForm);document.addEventListener('change',e=>{if(e.target.matches('#entryForm [name="payment"]'))syncEntryCard();if(e.target.matches('#recordCategoryFilter')){recordCategoryFilter=e.target.value;render()}if(e.target.matches('#recordPaymentFilter')){recordPaymentFilter=e.target.value;render()}if(e.target.matches('#recordCardFilter')){recordCardFilter=e.target.value;render()}});$('#recordSearch').addEventListener('input',e=>{recordSearch=e.target.value;render()});$('#periodPicker').addEventListener('click',()=>$('#monthDialog').showModal());$('#setMonth').addEventListener('click',e=>{e.preventDefault();if($('#monthInput').value){const m=$('#monthInput').value;selectedStart=paydayInMonth(Number(m.slice(0,4)),Number(m.slice(5,7))-1);$('#monthDialog').close();render()}});$('#simulationAmount').addEventListener('input',simulate);$('#simulationPayment').addEventListener('change',()=>{syncSimulationCard();simulate()});$('#simulationCard').addEventListener('change',simulate);$('#registerSimulation').addEventListener('click',registerSimulation);$('#backupData').addEventListener('click',backupData);$('#restoreData').addEventListener('click',()=>$('#restoreInput').click());$('#restoreInput').addEventListener('change',e=>restoreData(e.target.files[0]));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();
